
KEY_IS_DEV = "IS_DEV"
KEY_PORT = "PORT"

KEY_PARSE_APP_ID = "PARSE_APP_ID"
KEY_PARSE_MASTER_KEY = "PARSE_MASTER_KEY"
KEY_PARSE_API_KEY = "PARSE_API_KEY"

KEY_REDIS_HOST = "REDIS_HOST"
KEY_REDIS_PORT = "REDIS_PORT"
KEY_REDIS_DB = "REDIS_DB"
KEY_REDIS_PASSWORD = "REDIS_PASSWORD"

KEY_MODEL_CHKPT_PATH = "MODEL_CHKPT_PATH"
